# Generated by Django 3.0.5 on 2020-04-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200407_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='timing',
            field=models.CharField(max_length=250),
        ),
    ]
